=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocol.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.openremote.org" targetNamespace="http://www.openremote.org">
	<xsd:annotation>
		<xsd:documentation><![CDATA[
			OpenRemote protocol plugin describe XML, version 1.0.
			Authors:Allen Wei.
						
			This document describe all the useful infomation for the protocol plugin.
		]]></xsd:documentation>
	</xsd:annotation>

	<xsd:element name="openremote">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="protocol" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="protocol">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attr" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="displayName" type="xsd:string" use="required" />
			<xsd:attribute name="tagName" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="attr">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="validations" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="label" type="xsd:string" use="required" />
      <xsd:attribute name="tooltipMessage" type="xsd:string" use="optional"/>
			<xsd:attribute name="value" type="xsd:string" use="optional" />
			<xsd:attribute name="options" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="validations">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="allowBlank" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="maxLength" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="minLength" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="regex" minOccurs="0" maxOccurs="1"></xsd:element>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="allowBlank">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:boolean">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="maxLength">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:integer">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="minLength">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:integer">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="regex">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/isy99.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  Universal Devices ISY-99 gateway configuration for OpenRemote Designer.
 |
 |  Author: Andrew Ball
 +-->
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	
  <protocol displayName="ISY-99" tagName="isy99">
    <attr name="address" label="Address">
      <validations>
        <allowBlank>false</allowBlank>
        <regex message="Address is required">.*</regex>
      </validations>
    </attr>

    <attr name="command" label="Command">
      <validations>
        <allowBlank>false</allowBlank>
        <regex message="Command is required">.*</regex>
      </validations>
    </attr>
  </protocol>

</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/lutron_homeworks.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  Lutron Homeworks protocol configuration for OpenRemote Designer.
 |
 |  Author: Eric Bariaux
 +-->
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	<protocol displayName="Lutron HomeWorks" tagName="lutron_homeworks">
		<attr name="address" label="Address">
			<validations>
				<allowBlank>false</allowBlank>
				<!-- message is option -->
				<!-- <regex message="Address should be ">(\d\.){3}\d</regex> -->
			</validations>
		</attr>
		<attr name="command" label="Lutron Command">
			<validations>
				<allowBlank>false</allowBlank>
				<maxLength>16</maxLength>
				<regex message="Command must be one of RAISE, LOWER, STOP, FADE, STATUS_DIMMER, SCENE, STATUS_SCENE, PRESS, RELEASE, HOLD, DOUBLE_TAP, STATUS_KEYPADLED.">RAISE|LOWER|STOP|FADE|STATUS_DIMMER|SCENE|STATUS_SCENE|PRESS|RELEASE|HOLD|DOUBLE_TAP|STATUS_KEYPADLED</regex>
			</validations>
		</attr>
		<attr name="scene" label="Scene to select">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>2</maxLength>
				<regex message="Numbers only">\d+</regex>
			</validations>
		</attr>
		<attr name="key" label="Key to act on">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>2</maxLength>
				<regex message="Number only">\d+</regex>
			</validations>
		</attr>
		<attr name="level" label="Level to dim to">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>3</maxLength>
				<regex message="Number only, 0-100 range">\d+</regex>
			</validations>
		</attr>
	</protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/onewire.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 
 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.
 
 See the contributors.txt file in the distribution for a
 full listing of individual contributors.
 
 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.
 
 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 -->

<!--
 |  1-Wire protocol configuration for OpenRemote Designer.
 |
 |  Author: Jaroslav Misura
 +-->
<openremote xmlns="http://www.openremote.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openremote.org protocol.xsd">
    
    <protocol displayName="1-Wire Protocol" tagName="onewire">
        
        <attr name="hostname" label="Hostname">
            <validations>
                <allowBlank>false</allowBlank>
                <regex message="Hostname or IP address">^((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])|(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9]))$</regex>
            </validations>
        </attr>
        
        <attr name="port" label="Port">
            <validations>
                <allowBlank>false</allowBlank>
                <maxLength>5</maxLength>
                <regex message="Port number, only numbers allowed">[0-9]{1,5}</regex>
            </validations>
        </attr>
        
        <attr name="deviceAddress" label="Device address">
            <validations>
                <allowBlank>false</allowBlank>
                <regex message="Device address format">.*</regex>
            </validations>
        </attr>
        
        <attr name="filename" label="Sensor attribute" >
            <validations>
                <allowBlank>false</allowBlank>
                <regex message="Sensor attribute, such as temperature or humidity">.*</regex>
            </validations>
        </attr>
        
	    <!--
	     |  Optional definition of the temperature scale to use. Default: Celsius
	     +-->
	    <attr name = "temperatureScale" label = "Temp. scale" options="Celsius,Fahrenheit,Kelvin,Rankine">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
	    </attr>
        
        <attr name="pollingInterval" label="Polling interval" tooltipMessage = "Polling interval in form of (1s, 1m, 1h) or just milliseconds">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/telnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 
 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.
 
 See the contributors.txt file in the distribution for a
 full listing of individual contributors.
 
 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.
 
 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 -->

<!--
 Telnet Protocol Implementation.
 
 Author: Marcus Redeker
 Author: Richard Turner
 -->
<openremote xmlns = "http://www.openremote.org" 
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation = "http://www.openremote.org protocol.xsd">
    
    <protocol displayName = "Telnet" tagName = "telnet">
        
        <attr name = "ipAddress" label = "IP Address">
            <validations>
                <allowBlank>false</allowBlank>
                <regex message = "IP addresses are usually represented in dot-decimal notation (four numbers, each ranging from 0 to 255, separated by dots, e.g. 208.77.188.166)">.*</regex>
            </validations>
        </attr>
        
        <attr name = "port" label = "Port">
            <validations>
                <allowBlank>false</allowBlank>
                <maxLength>5</maxLength>
                <regex message = "Port must be an integer number.">\d+</regex>
            </validations>
        </attr>
        
        <attr name = "command" label = "Command">
            <validations>
                <allowBlank>false</allowBlank>
                <maxLength>4000</maxLength>
                <regex message = "Command is necessary">.*\w+.*</regex>
            </validations>
        </attr>
		
        <attr name = "timeout" label = "Read Timeout (s)">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>2</maxLength>
                <regex message = "Timeout in seconds">\d+</regex>
            </validations>
        </attr>
        
        <attr name = "statusFilter" label = "Read Regex Filter">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>1000</maxLength>
                <regex message = "Status Filter Regular Expression">.*</regex>
            </validations>
        </attr>
        
        <attr name = "statusFilterGroup" label = "Read Regex Group">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>3</maxLength>
                <regex message = "This is the regex group number that contains the value to return, it must be an integer.">\d+</regex>
            </validations>
        </attr>
		
        <attr name = "statusDefault" label = "Default Read Response">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>100</maxLength>
                <regex message = "Default response if regex match fails.">.*</regex>
            </validations>
        </attr>
        
        <attr name="pollingInterval" label="Polling interval" tooltipMessage="Polling interval in form of (1s, 1m, 1h) or just milliseconds">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/virtual.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  In-memory, virtual 'dummy' commands that can be used in testing/demoing.
 |  These commands won't attempt to create physical connections to any devices,
 |  all state and responses are returned from the controller's in-memory state.
 |
 |  Author: Juha Lindfors
 +-->
<openremote xmlns = "http://www.openremote.org"
            xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
	          xsi:schemaLocation = "http://www.openremote.org protocol.xsd">

	<protocol displayName = "In-memory Virtual Command" tagName = "virtual">

    <!--
     | Mandatory command parameter.
     +-->
    <attr name = "command" label = "Command">
      <validations>
        <allowBlank>false</allowBlank>
        <maxLength>254</maxLength>

        <regex message = "Use on/off or status">on|On|ON|off|Off|OFF|status|Status|STATUS</regex>

      </validations>
    </attr>


    <!--
     | Mandatory address parameter.
     +-->
    <attr name = "address" label = "Address">
      <validations>
        <allowBlank>false</allowBlank>
        <maxLength>254</maxLength>

        <regex message="Use any arbitrary address string. Commands that are used in the same switch component should use an identical address.">[a-zA-Z]*</regex>

      </validations>
    </attr>
  </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/test/org/openremote/modeler/protocol/fixture/knx.xml
<?xml version="1.0" encoding="UTF-8"?>
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	<protocol displayName="KNX" tagName="knx">
		<attr name="groupAddress" label="Group Address" tooltipMessage="KNX Group Address">
			<validations>
				<allowBlank>false</allowBlank>
				<!-- message is option -->
				<regex message="group address should be 1.4.1.4">(\d\.){3}\d</regex>
			</validations>
		</attr>
		<attr name="command" label="KNX Command">
			<validations>
				<allowBlank>false</allowBlank>
				<maxLength>10</maxLength>
				<regex>\w*</regex>
			</validations>
		</attr>
	</protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/samsungtv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 
 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.
 
 See the contributors.txt file in the distribution for a
 full listing of individual contributors.
 
 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.
 
 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 -->

<!--
 |  Samsung Smart-TV protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openremote.org protocol.xsd">
    
    <protocol displayName="Samsung TV Remote" tagName="samsungTV">
        
        <attr name="keyCode" label="KeyCode" tooltipMessage="The KeyCode which is sent to the TV, BD-Player, ...">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>
        
        <attr name="ipAddress" label="IP-Address" tooltipMessage="Can be used to control multiple devices">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>
