=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocol.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.openremote.org" targetNamespace="http://www.openremote.org">
	<xsd:annotation>
		<xsd:documentation><![CDATA[
			OpenRemote protocol plugin describe XML, version 1.0.
			Authors:Allen Wei.
						
			This document describe all the useful infomation for the protocol plugin.
		]]></xsd:documentation>
	</xsd:annotation>

	<xsd:element name="openremote">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="protocol" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="protocol">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attr" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="displayName" type="xsd:string" use="required" />
			<xsd:attribute name="tagName" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="attr">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="validations" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="label" type="xsd:string" use="required" />
      <xsd:attribute name="tooltipMessage" type="xsd:string" use="optional"/>
			<xsd:attribute name="value" type="xsd:string" use="optional" />
			<xsd:attribute name="options" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="validations">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="allowBlank" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="maxLength" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="minLength" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="regex" minOccurs="0" maxOccurs="1"></xsd:element>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="allowBlank">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:boolean">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="maxLength">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:integer">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="minLength">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:integer">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="regex">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/udp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
  UDP Transport protocol (send-only).

  Author: Richard Turner
-->
<openremote xmlns = "http://www.openremote.org" 
            xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
	    xsi:schemaLocation = "http://www.openremote.org protocol.xsd">

  <protocol displayName = "UDP" tagName = "udp">

    <attr name = "ipAddress" label = "IP Address">
      <validations>
        <allowBlank>false</allowBlank>
          <regex message="Must be a valid IPv4 or IPv6 address or a fully qualified domain name">(?:(?:1\d{0,2}|[3-9]\d?|2(?:[0-5]{1,2}|\d)?|0)\.){3}(?:1\d{0,2}|[3-9]\d?|2(?:[0-5]{1,2}|\d)?|0)|(^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$)|(^([0-9a-f]{1,4}:){1,1}(:[0-9a-f]{1,4}){1,6}$)|(^([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}$)|(^([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}$)|(^([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}$)|(^([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}$)|(^([0-9a-f]{1,4}:){1,6}(:[0-9a-f]{1,4}){1,1}$)|(^(([0-9a-f]{1,4}:){1,7}|:):$)|(^:(:[0-9a-f]{1,4}){1,7}$)|(^((([0-9a-f]{1,4}:){6})(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3})$)|(^(([0-9a-f]{1,4}:){5}[0-9a-f]{1,4}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3})$)|(^([0-9a-f]{1,4}:){5}:[0-9a-f]{1,4}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)|(^([0-9a-f]{1,4}:){1,1}(:[0-9a-f]{1,4}){1,4}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)|(^([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,3}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)|(^([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,2}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)|(^([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,1}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)|(^(([0-9a-f]{1,4}:){1,5}|:):(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)|(^:(:[0-9a-f]{1,4}){1,5}:(25[0-5]|2[0-4]\d|[0-1]?\d?\d)(\.(25[0-5]|2[0-4]\d|[0-1]?\d?\d)){3}$)</regex>
      </validations>
    </attr>

    <attr name = "port" label = "Port">
      <validations>
        <allowBlank>false</allowBlank>
        <maxLength>5</maxLength>
        <regex message = "Port must be an integer number.">\d+</regex>
      </validations>
    </attr>

    <attr name = "command" label = "Command">
      <validations>
        <allowBlank>false</allowBlank>
        <maxLength>4000</maxLength>
        <regex message = "Command is necessary">.*\w+.*</regex>
      </validations>
    </attr>

  </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/datetime.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  DateTime protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">

    <protocol displayName="DateTime Protocol" tagName="datetime">

        <attr name="latitude" label="Latitude for Sunrise/Sunset calculation">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>

        <attr name="longitude" label="Longitude for Sunrise/Sunset calculation">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>

        <attr name="timezone" label="Timezone todo time corrections. If not set, default is taken.">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="command" label="What should be calculated / returned?">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>
        
        <attr name="format" label="How should date/time values be formatted?">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/domintell.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  Domintell protocol configuration for OpenRemote Designer.
 |
 |  Author: Eric Bariaux
 +-->
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	<protocol displayName="Domintell" tagName="domintell">
		<attr name="module_type" label="Module Type" options="BIR,DMR,TRP,DIM,D10,TSB,TE1,TE2,LC3,PBL" tooltipMessage="Type of the module to control">
			<validations>
				<allowBlank>false</allowBlank>
			</validations>
		</attr>
		<attr name="address" label="Address" tooltipMessage="Address of the module to control">
			<validations>
				<allowBlank>false</allowBlank>
				<!-- message is option -->
				<!-- <regex message="Address should be ">(\d\.){3}\d</regex> -->
			</validations>
		</attr>
		<attr name="command" label="Domintell Command" options="ON,OFF,TOGGLE,STATUS,FADE,READ_CURRENT_TEMP,READ_SET_POINT,SET_SET_POINT,READ_MODE,SET_MODE,READ_PRESET_SET_POINT">
			<validations>
				<allowBlank>false</allowBlank>
			</validations>
		</attr>
		<attr name="output" label="Output">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>1</maxLength>
				<regex message="Number only">\d+</regex>
			</validations>
		</attr>
		<attr name="level" label="Level to dim to">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>3</maxLength>
				<regex message="Number only, 0-100 range">\d+</regex>
			</validations>
		</attr>
		<attr name="set_point" label="Temperature set point">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>5</maxLength>
				<regex message="Float number only">\d+(.\d+)*</regex>
			</validations>
		</attr>
		<attr name="temp_mode" label="Temperature control mode">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>7</maxLength>
				<regex message="Must be one of ABSENCE, AUTO, COMFORT or FROST">ABSENCE|AUTO|COMFORT|FROST</regex>
			</validations>
		</attr>
	</protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/udpListener.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  UDPListener protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">

    <protocol displayName="UDPListener" tagName="udpListener">

        <attr name="port" label="UDP port" tooltipMessage="The UDP port where the controller will listen for packages">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>

        <attr name="regex" label="RegularExpression" tooltipMessage="Regex to find a match in the received UDP packet" >
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/wol.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  Wake-On-Lan protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">

    <protocol displayName="Wake-On-Lan Protocol" tagName="wol">

        <attr name="macAddress" label="MAC address">
            <validations>
                <allowBlank>false</allowBlank>
                <regex message="MAC address of the computer to wake">.*</regex>
            </validations>
        </attr>

        <attr name="broadcastIp" label="Broadcast IP" >
            <validations>
                <allowBlank>false</allowBlank>
                <regex message="Broadcast IP of the network where the computer to wake is located, eg 192.168.1.255">.*</regex>
            </validations>
        </attr>

    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/knx.xml
<?xml version="1.0" encoding="UTF-8"?>
<openremote xmlns = "http://www.openremote.org"
            xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation = "http://www.openremote.org protocol.xsd">

  <protocol displayName = "KNX" tagName = "knx">

    <attr name = "groupAddress" label = "Group Address">
      <validations>
        <allowBlank>false</allowBlank>
        <!-- message is option -->
        <!-- <regex message="group address should be 1.4.1.4">(\d\.){3}\d</regex> -->
      </validations>
    </attr>

    <attr name = "command" label = "KNX Command">
      <validations>
        <allowBlank>false</allowBlank>
        <maxLength>20</maxLength>
        <regex message = "Command is necessary. ">.*\w+.*</regex>
      </validations>
    </attr>

    <attr name = "DPT" label = "KNX DataPoint Type (DPT)">
      <validations>
        <allowBlank>false</allowBlank>
        <maxLength>8</maxLength>
        <!-- <regex message = "Must have a valid DPT identifier (n.mmm)">[1-9].[0-9][0-9][0-9]</regex> -->
      </validations>
    </attr>

  </protocol>
  
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/x10.xml
<?xml version="1.0" encoding="UTF-8"?>
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	<protocol displayName="X10" tagName="x10">
		<attr name="address" label="Address">
			<validations>
				<allowBlank>false</allowBlank>
			</validations>
		</attr>
		<attr name="command" label="Command">
			<validations>
				<allowBlank>false</allowBlank>
				<maxLength>10</maxLength>
				<regex message="Command is necessary">.*\w+.*</regex>
			</validations>
		</attr>
	</protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/lagarto.xml
<?xml version="1.0" encoding="UTF-8"?>
<openremote xmlns="http://www.openremote.org" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">
  <protocol displayName="panStamp lagarto" tagName="lagarto">
    <attr name="network" label="Server name">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>
    <attr name="epid" label="Endpoint ID">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>
    <attr name="value" label="New value">
      <validations>
        <allowBlank>true</allowBlank>
      </validations>
    </attr>
  </protocol>
</openremote>
