=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocol.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.openremote.org" targetNamespace="http://www.openremote.org">
	<xsd:annotation>
		<xsd:documentation><![CDATA[
			OpenRemote protocol plugin describe XML, version 1.0.
			Authors:Allen Wei.
						
			This document describe all the useful infomation for the protocol plugin.
		]]></xsd:documentation>
	</xsd:annotation>

	<xsd:element name="openremote">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="protocol" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="protocol">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="attr" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="displayName" type="xsd:string" use="required" />
			<xsd:attribute name="tagName" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="attr">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="validations" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
			<xsd:attribute name="label" type="xsd:string" use="required" />
      <xsd:attribute name="tooltipMessage" type="xsd:string" use="optional"/>
			<xsd:attribute name="value" type="xsd:string" use="optional" />
			<xsd:attribute name="options" type="xsd:string" use="optional" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="validations">
		<xsd:complexType>
			<xsd:all>
				<xsd:element ref="allowBlank" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="maxLength" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="minLength" minOccurs="0" maxOccurs="1"></xsd:element>
				<xsd:element ref="regex" minOccurs="0" maxOccurs="1"></xsd:element>
			</xsd:all>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="allowBlank">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:boolean">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="maxLength">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:integer">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="minLength">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:integer">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="regex">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="message" type="xsd:string" use="optional" />
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/huebridge.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 
 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.
 
 See the contributors.txt file in the distribution for a
 full listing of individual contributors.
 
 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.
 
 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 -->

<!--
 |  HUE Bridge protocol configuration for OpenRemote Designer.
 |
 |  Author: TASS Technology Solutions - www.tass.nl
 +-->
<openremote xmlns = "http://www.openremote.org"
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation = "http://www.openremote.org protocol.xsd">
    
    <protocol displayName = "Hue bridge" tagName = "huebridge">
        
		 <!--
         |  IP of the Hue bridge, this field can be left empty when set in the config for controller.
         +-->
        <attr name = "bridgeip" label = "Bridge Ip" tooltipMessage="The Ip address of the Hue Bridge">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>16</maxLength>
                <regex message = "Enter valid IP (IPV4) address">\b^$|(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b</regex>
            </validations>
        </attr>

		 <!--
         |  Key/Username of the Hue bridge, this field can be left empty when set in the config for controller.
         +-->
        <attr name = "key" label = "Bridge Key" tooltipMessage="The Key provided by the Hue Bridge after authenticating the controller">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>32</maxLength>              
            </validations>
        </attr>
		
		 <!--
         |  ID of the light that needs to be controlled.
         +-->		
		<attr name = "lightid" label = "Id of the lamp" tooltipMessage="The id of the light that the hue bridge creates and uses for controlling the light. (id normally starts at 1)">
            <validations>
                <allowBlank>false</allowBlank>
                <maxLength>3</maxLength>              
            </validations>
        </attr>

		 <!--
         |  Put the light on or off.
         +-->		
        <attr name = "power" label = "On or OFF" options="On,Off" tooltipMessage="Should the light turn on or Off">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>        
		
		 <!--
         |  What Hue Color should the lamp be set to
         +-->		
		<attr name = "color" label = "Hue Color" tooltipMessage = "Sets the color of the light to this value, must be between 0 and 65535." >
            <validations>
                <allowBlank>true</allowBlank>
               	<!--<regex message = "Enter valid Hue value"></regex>-->
            </validations>
        </attr>
		
		 <!--
         |  Set the brightness of the lamp
         +-->		
		<attr name = "brightness" label = "Brightness"  tooltipMessage = "Sets the brightness of the light to this value, must be between 0 and 255." >
            <validations>
                <allowBlank>true</allowBlank>            
				<!--<regex message = "Enter valid Hue value"></regex>-->
            </validations>
        </attr>
		
		 <!--
         |  Set the saturation of the lamp
         +-->		
		<attr name = "saturation" label = "Saturation"  tooltipMessage = "Sets the saturarion of the light to this value, must be between 0 and 255.">
            <validations>
                <allowBlank>true</allowBlank>          
			
            </validations>
        </attr>		

		 <!--
         |  Is this command used for a sensor? yes then a sensor for what
         +-->		
		 <attr name="sensor" label="Sensor setting" options="Power,Color,Brightness,Saturation" tooltipMessage = "Needs to be set when creating a sensor.">
            <validations>			
                <allowBlank>true</allowBlank>
            </validations>
        </attr>

		 <!--
         |  Polling interval of the sensor
         +-->		
        <attr name="pollingInterval" label="Polling interval" tooltipMessage = "Polling interval in form of (1s, 1m, 1h) or just milliseconds. Needs to be set when creating a sensor.">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
    </protocol>
    
</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/shellexe.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 
 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.
 
 See the contributors.txt file in the distribution for a
 full listing of individual contributors.
 
 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.
 
 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 -->

<!--
 |  ShellExe protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openremote.org protocol.xsd">
    
    <protocol displayName="Shell execution protocol" tagName="shellexe">
        
        <attr name="commandPath" label="Path" tooltipMessage="Full path to executable">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>
        
        <attr name="commandParams" label="Command parameter" tooltipMessage="Additional parameter added to the command">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="pollingInterval" label="Polling interval" tooltipMessage="Polling interval in form of (1s, 1m, 1h) or just milliseconds">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="regex" label="RegularExpression" tooltipMessage="RegularExpression to parse value out of result" >
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="sensorNamesList" label="Sensor names" tooltipMessage="Semicolon seperated list of sensor names. Uses the regex to split result on multiple sensors" >
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/http.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 
 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.
 
 See the contributors.txt file in the distribution for a
 full listing of individual contributors.
 
 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.
 
 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 
 -->

<!--
 |  HTTP protocol configuration for OpenRemote Designer.
 |
 |  Author: Juha Lindfors
 |  Author: Marcus Redeker
 +-->
<openremote xmlns = "http://www.openremote.org"
    xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation = "http://www.openremote.org protocol.xsd">
    
    <protocol displayName = "HTTP" tagName = "http">
        
        <!--
         | Mandatory URL parameter for HTTP protocol.
         +-->
        <attr name = "url" label = "URL">
            <validations>
                <allowBlank>false</allowBlank>
                <maxLength>4000</maxLength>
                <regex message = "Enter valid HTTP URL">.*</regex>
            </validations>
        </attr>
        
        <!--
         |  Optional definition of the HTTP method to use. This is useful if a REST API is called. Default: GET
         +-->
        <attr name = "method" label = "HTTP Method" options="GET,POST,PUT,DELETE" tooltipMessage="Optional definition of the HTTP method. Default: GET">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <!--
         |  Data which is added to Post and Put methods as workload. For JSON REST API's this can be the JSON data
         +-->
        <attr name = "workload" label = "Workload" tooltipMessage="Data which is added to Post and Put method bodies." >
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <!--
         | Optional username parameter for HTTP URLs that expect HTTP Basic authentication header.
         |
         | (Since R3518)
         +-->
        <attr name = "username" label = "Username">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>254</maxLength>
                <regex
                    message = "Only needed for URLs that require authentication credentials. Can be left empty otherwise." >.*</regex>
            </validations>
        </attr>
        
        <!--
         | Optional password parameter for HTTP URLs that expect HTTP Basic authentication header.
         |
         | (Since R3518)
         +-->
        <attr name = "password" label = "Password">
            <validations>
                <allowBlank>true</allowBlank>
                <maxLength>254</maxLength>
                <regex
                    message = "Only needed for URLs that require authentication credentials. Can be left empty otherwise.">.*</regex>
            </validations>
        </attr>
        
        <attr name="xpath" label="XPath Expression" tooltipMessage = "XPath Expression to parse value out of XML result">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="regex" label="RegularExpression" tooltipMessage = "RegularExpression to parse value out of result" >
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="pollingInterval" label="Polling interval" tooltipMessage = "Polling interval in form of (1s, 1m, 1h) or just milliseconds">
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
        <attr name="jsonpath" label="JSONPath Expression" tooltipMessage = "JSONPath Expression to parse value out of JSON result" >
            <validations>
                <allowBlank>true</allowBlank>
            </validations>
        </attr>
        
    </protocol>
    
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/infrared.xml
<?xml version="1.0" encoding="UTF-8"?>
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	<protocol displayName="Infrared" tagName="ir">
		<attr name="name" label="Name">
			<validations>
				<allowBlank>false</allowBlank>
			</validations>
		</attr>
		<attr name="command" label="IR Command">
			<validations>
				<allowBlank>false</allowBlank>
				<maxLength>10</maxLength>
				<regex message="Command is necessary">\w+</regex>
			</validations>
		</attr>
	</protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/dsc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
  DSC IT-100 Security System Protocol.

  Uses IP-based protocol and requires IP-to-Serial interface to integrate
  with DSC IT-100 security system.

  Author: Greg Rapp
-->
<openremote xmlns="http://www.openremote.org" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">

  <protocol displayName="DSC IT-100" tagName="dscit100">

    <attr name="address" label="IT-100 Address">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>

    <attr name="command" label="Command">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>

    <attr name="target" label="Target">
      <validations>
        <allowBlank>false</allowBlank>
    	<maxLength>3</maxLength>
        <regex message="Only numbers allowed">[0-9]{1,3}</regex>      
      </validations>
    </attr>

    <attr name="code" label="Security Code">
      <validations>
        <allowBlank>true</allowBlank>
      </validations>
    </attr>

  </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/apache-tomcat-6.0.18/webapps/modeler/WEB-INF/classes/protocols/zwave.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2011, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  Z-Wave protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">

    <protocol displayName="Z-Wave" tagName="zwave">

        <attr name="nodeId" label="Z-Wave nodeID" tooltipMessage="The nodeID the controller assigned to this device upon inclusion">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>


        <attr name="command" label="Command" tooltipMessage="Currently 'on', 'off', 'dim' and 'status' for switches and dimmer work">
            <validations>
                <allowBlank>false</allowBlank>
            </validations>
        </attr>
        
    </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/protocols/protocols/hsc40.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  HSC IP gateway (HSC-40) protocol configuration for OpenRemote Designer.
 |
 |  Author: Marcus Redeker
 +-->
<openremote xmlns="http://www.openremote.org"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.openremote.org protocol.xsd">

  <protocol displayName="HSC Z-Wave IP gateway" tagName="hsc40">

    <attr name="deviceId" label="Hex-Value of device eg. 0x11">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>

    <attr name="portId" label="Hex-Value of port eg. 0x01">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>

    <attr name="command" label="Command to use eg. 'on', 'off' or 'status'">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>

    <attr name="deviceType" label="Z-Wave device type, eg. Switch, Dimmer, ...">
      <validations>
        <allowBlank>false</allowBlank>
      </validations>
    </attr>

  </protocol>
</openremote>

=== TASSBV/OpenRemoteHueBridge/Designer_2_13_9_Rosemary_20130330/war/WEB-INF/classes/protocols/amx_ni.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

 OpenRemote, the Home of the Digital Home.
 Copyright 2008-2012, OpenRemote Inc.

 See the contributors.txt file in the distribution for a
 full listing of individual contributors.

 This is free software; you can redistribute it and/or modify it
 under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 3.0 of
 the License, or (at your option) any later version.

 This software is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 You should have received a copy of the GNU General Public
 License along with this software; if not, write to the Free
 Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 02110-1301 USA, or see the FSF site: http://www.fsf.org.

-->

<!--
 |  AMX Controller protocol configuration for OpenRemote Designer.
 |
 |  Author: Eric Bariaux
 +-->
<openremote xmlns="http://www.openremote.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.openremote.org protocol.xsd">
	<protocol displayName="AMX Controller" tagName="amx_ni">
		<attr name="command" label="AMX Command" options="ON,OFF,PULSE,CHANNEL_STATUS,SEND_LEVEL,LEVEL_STATUS,SEND_COMMAND,COMMAND_READ,SEND_STRING,STRING_READ">
			<validations>
				<allowBlank>false</allowBlank>
			</validations>
		</attr>
		<attr name="deviceIndex" label="Device index" tooltipMessage="One-based index of device to control in devices array passed to AMX module">
			<validations>
				<allowBlank>false</allowBlank>
			</validations>
		</attr>
		<attr name="channel" label="Channel" tooltipMessage="Channel used for ON, OFF, PULSE and CHANNEL_STATUS commands">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>5</maxLength>
				<regex message="Numbers only">\d+</regex>
			</validations>
		</attr>
		<attr name="level" label="Level" tooltipMessage="Level used for SEND_LEVEL and LEVEL_STATUS commands">
			<validations>
				<allowBlank>true</allowBlank>
				<maxLength>5</maxLength>
				<regex message="Numbers only">\d+</regex>
			</validations>
		</attr>
		<attr name="value" label="Value" tooltipMessage="Value used for SEND_LEVEL, SEND_COMMAND and SEND_STRING commands">
			<validations>
				<allowBlank>true</allowBlank>
			</validations>
		</attr>
                <attr name = "statusFilter" label = "Read Regex Filter">
                    <validations>
                        <allowBlank>true</allowBlank>
                        <maxLength>1000</maxLength>
                        <regex message = "Status Filter Regular Expression">.*</regex>
                    </validations>
                </attr>
                <attr name = "statusFilterGroup" label = "Read Regex Group">
                    <validations>
                        <allowBlank>true</allowBlank>
                        <maxLength>3</maxLength>
                        <regex message = "This is the regex group number that contains the value to return, it must be an integer.">\d+</regex>
                    </validations>
                </attr>
	</protocol>
</openremote>
